# SMS Spam Classification using Word2Vec

In [ ]:
import pandas as pd

message = pd.read_csv(
    'C:/Users/ASUS/Documents/nlp/data/spam.csv',
    sep='\t',
    names=['label', 'message'],
    encoding='latin-1'
)

print(message.head())

                                               label  message
0                                           v1,v2,,,      NaN
1  ham,"Go until jurong point, crazy.. Available ...      NaN
2               ham,Ok lar... Joking wif u oni...,,,      NaN
3  spam,Free entry in 2 a wkly comp to win FA Cup...      NaN
4  ham,U dun say so early hor... U c already then...      NaN


# Data Cleaning

In [2]:

message['message']=message['label'].str.split(',').str[1]
message['label'] = message['label'].str.split(',').str[0]

In [3]:
message=message.drop(message.index[0])

In [4]:
import re

import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## Creating list of word from Corpus

In [ ]:

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

wl = WordNetLemmatizer()

all_stopwords = set(stopwords.words('english'))

corpus = []

for i in range(0, len(message)):
    
    review = re.sub('[^a-zA-Z]', ' ', message['message'].iloc[i])
    
    review = review.lower()
    
    review = review.split()
    
    review = [wl.lemmatize(word) for word in review if word not in all_stopwords]
    #DO NOT JOIN THE WORDS, JUST APPEND THE WORDS TO THE CORPUS
    
    corpus.append(review)

In [27]:
corpus


[['go', 'jurong', 'point'],
 ['ok', 'lar', 'joking', 'wif', 'u', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'c',
  'apply'],
 ['u', 'dun', 'say', 'early', 'hor', 'u', 'c', 'already', 'say'],
 ['nah', 'think', 'go', 'usf'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
  'prize',
  'reward',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour'],
 ['mobile',
  'month',
  'u',
  'r',
 

In [10]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:

import gensim


import gensim.downloader as api
wv = api.load('word2vec-google-news-300')



In [17]:
from nltk import sent_tokenize, word_tokenize
from gensim.utils import simple_preprocess 

## Alternate way to create a list of words from the corpus

In [ ]:
word=[] 
for sentence in corpus:
    sent_token=sent_tokenize(sentence)
    for sent in sent_token:
        word.append(simple_preprocess(sent))

## Model Training

In [82]:
from gensim.models import Word2Vec, KeyedVectors
model=gensim.models.Word2Vec(corpus, vector_size=100, window=5, min_count=1, workers=4)

In [31]:
model.wv.index_to_key

['u',
 'call',
 'ur',
 'get',
 'ok',
 'gt',
 'lt',
 'free',
 'go',
 'day',
 'good',
 'come',
 'know',
 'time',
 'like',
 'got',
 'want',
 'r',
 'send',
 'going',
 'today',
 'lor',
 'text',
 'k',
 'one',
 'da',
 'sorry',
 'txt',
 'home',
 'love',
 'need',
 'hi',
 'tell',
 'p',
 'mobile',
 'dont',
 'stop',
 'new',
 'see',
 'take',
 'dear',
 'reply',
 'n',
 'still',
 'week',
 'c',
 'phone',
 'think',
 'message',
 'msg',
 'pls',
 'back',
 'hey',
 'oh',
 'co',
 'wat',
 'please',
 'say',
 'well',
 'claim',
 'min',
 'much',
 'make',
 'number',
 'night',
 'work',
 'yes',
 'thing',
 'great',
 'b',
 'e',
 'give',
 'right',
 'already',
 'win',
 'yeah',
 'really',
 'tone',
 'said',
 'hope',
 'ask',
 'way',
 'later',
 'im',
 'tomorrow',
 'meet',
 'friend',
 'babe',
 'lol',
 'www',
 'happy',
 'year',
 'find',
 'urgent',
 'cash',
 'prize',
 'thanks',
 'let',
 'every',
 'buy',
 'service',
 'last',
 'life',
 'morning',
 'anything',
 'also',
 'com',
 'would',
 'nokia',
 'cant',
 'sent',
 'contact',
 'pi

In [32]:
model.epochs

5

In [35]:
model.corpus_count

5574

In [39]:
model.wv.similar_by_word('happy')

[('thing', 0.9991896152496338),
 ('one', 0.9990954995155334),
 ('like', 0.999078631401062),
 ('u', 0.999043345451355),
 ('com', 0.9990418553352356),
 ('time', 0.9990417957305908),
 ('hope', 0.9990318417549133),
 ('got', 0.9990314841270447),
 ('b', 0.9990257024765015),
 ('see', 0.9990161061286926)]

In [34]:
pip install tqdm

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv], axis=0)

In [ ]:
##tqdm is a library that allows us to create progress bars for our loops, which can be helpful when processing large datasets. In this case, we are using tqdm to show the progress of converting each sentence in the corpus into its average word2vec representation.
from tqdm import tqdm   
X = []
for sentence in tqdm(corpus):
    X.append(avg_word2vec(sentence))


  0%|          | 0/5574 [00:00<?, ?it/s]c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\_methods.py:144: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5574/5574 [00:00<00:00, 10046.57it/s]


In [48]:
X

[array([-0.09223447,  0.20011838,  0.04325318,  0.01043722,  0.01466919,
        -0.41266632,  0.1506352 ,  0.4604453 , -0.18738206, -0.11788874,
        -0.0672624 , -0.38522223, -0.10562982,  0.12274442,  0.08139469,
        -0.14438216,  0.02665409, -0.24519795, -0.0568426 , -0.41686973,
         0.14013958,  0.04454475,  0.09592629, -0.05019812, -0.06072737,
        -0.05752531, -0.17176026, -0.17826192, -0.20336367,  0.01621013,
         0.2177306 ,  0.05262341,  0.05370804, -0.20445077, -0.05456115,
         0.18555462,  0.02363203, -0.20728435, -0.15241277, -0.4032922 ,
         0.01606134, -0.21497226, -0.1556844 , -0.01711178,  0.2264322 ,
        -0.01779707, -0.09149752,  0.0328029 ,  0.10079811,  0.21013005,
         0.09190244, -0.19391654, -0.06284595, -0.0068536 , -0.09209637,
         0.14181924,  0.12483368, -0.01527475, -0.18805678,  0.07948913,
         0.02407928,  0.09904113, -0.01851042, -0.04268835, -0.24289167,
         0.17187373,  0.07494128,  0.15522741, -0.3

In [44]:
len(X)

5574

In [ ]:
##data cleaning to remove the None values from the list X and convert it to a numpy array

X_clean = []

for item in X:
    if isinstance(item, np.ndarray):
        X_clean.append(item)

X_clean = np.array(X_clean)

print(X_clean.shape)

(5537, 100)


In [ ]:
X_new=X_clean

(5537, 100)

In [ ]:
##data cleaning to remove those value from the message[labels] which are not present in the corpus and then get the labels for those values
y=message[list(map(lambda x:len(x)>0,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values 
y 

array([ True,  True, False, ...,  True,  True,  True], shape=(5537,))

In [73]:
df=pd.DataFrame(X_new)
df['label']=y
df.head()


,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,label
0,-0.092234,0.200118,0.043253,0.010437,0.014669,-0.412666,0.150635,0.460445,-0.187382,-0.117889,...,0.094048,0.048539,0.114725,0.396779,0.265885,0.133104,-0.215141,0.049768,-0.010832,True
1,-0.074492,0.175963,0.040939,0.012006,0.002417,-0.358037,0.129617,0.411819,-0.164945,-0.101175,...,0.086682,0.046517,0.104489,0.351113,0.228937,0.110130,-0.195313,0.040882,-0.005619,True
2,-0.065664,0.150114,0.036069,0.009149,0.010725,-0.314362,0.111101,0.363542,-0.138707,-0.090280,...,0.071226,0.039538,0.091375,0.302114,0.202465,0.097045,-0.165871,0.031315,-0.007076,False
3,-0.124392,0.290681,0.069945,0.015183,0.008412,-0.599098,0.214798,0.682078,-0.268856,-0.172618,...,0.139611,0.072309,0.174469,0.586221,0.383160,0.185458,-0.323065,0.066027,-0.012467,True
4,-0.089743,0.200783,0.051018,0.011006,0.007980,-0.408280,0.149185,0.468407,-0.189637,-0.112707,...,0.101903,0.048236,0.118940,0.405442,0.264233,0.129406,-0.218240,0.048692,-0.007582,True


In [ ]:
df.shape


(5537, 101)

In [76]:
X=df[df.columns[:-1]]
y=df['label']

## Train Test Split

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [79]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

## Random Forest Classifier

In [78]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [80]:
classifier.predict(X_test)

array([ True,  True,  True, ...,  True,  True,  True], shape=(1108,))

In [81]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


              precision    recall  f1-score   support

       False       1.00      0.65      0.78       141
        True       0.95      1.00      0.97       967

    accuracy                           0.95      1108
   macro avg       0.98      0.82      0.88      1108
weighted avg       0.96      0.95      0.95      1108

[[ 91  50]
 [  0 967]]
0.9548736462093863
